const C=window.WEALTHOS_CONFIG,sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY),$=x=>document.getElementById(x),money=n=>"৳"+Math.round(+n||0).toLocaleString("en-IN");let user,inv=[],tx=[],lc,dc;
const toast=m=>{let t=$("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",2500)},fv=(m,r,y)=>{let n=y*12,i=r/1200;return i?m*((Math.pow(1+i,n)-1)/i):m*n},esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function state(){let {data:{session}}=await sb.auth.getSession();user=session?.user;$("auth").classList.toggle("hide",!!user);$("app").classList.toggle("hide",!user);if(user){$("who").textContent=user.email;await load()}}
$("login").onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});error?toast(error.message):state()};
$("signup").onclick=async()=>{let {error}=await sb.auth.signUp({email:$("email").value,password:$("password").value});toast(error?error.message:"Account created — email confirmation থাকলে inbox check করুন।")};
$("logout").onclick=async()=>{await sb.auth.signOut();state()};
async function load(){let [a,b]=await Promise.all([sb.from("investments").select("*").order("created_at"),sb.from("transactions").select("*").order("transaction_date",{ascending:false})]);if(a.error)return toast(a.error.message);if(b.error)return toast(b.error.message);inv=a.data||[];tx=b.data||[];render()}
function render(){let planned=0,projected=0,max=0;$("cards").innerHTML="";inv.forEach(x=>{let p=+x.monthly_amount*+x.duration_years*12,f=fv(+x.monthly_amount,+x.expected_return,+x.duration_years);planned+=p;projected+=f;max=Math.max(max,+x.duration_years);$("cards").insertAdjacentHTML("beforeend",`<article class="card"><div class="cardTop"><h3>${esc(x.name)}</h3><span class="tag">${esc(x.type)}</span></div><div class="big">${money(f)}</div><div class="muted">PROJECTED MATURITY</div><div class="metrics"><div class="metric"><span>MONTHLY</span><b>${money(x.monthly_amount)}</b></div><div class="metric"><span>RETURN</span><b>${x.expected_return}%</b></div><div class="metric"><span>YEARS</span><b>${x.duration_years}</b></div><div class="metric"><span>CURRENT</span><b>${money(x.current_value)}</b></div></div><div class="cardBtns"><button onclick="editInv('${x.id}')">Edit</button><button class="danger" onclick="delInv('${x.id}')">Delete</button></div></article>`)});
if(!inv.length)$("cards").innerHTML='<article class="panel muted">+ Add investment দিয়ে শুরু করুন।</article>';$("planned").textContent=money(planned);$("projected").textContent=money(projected);$("profit").textContent=money(projected-planned);$("actual").textContent=money(tx.reduce((s,x)=>s+ +x.amount,0));$("heroValue").textContent=money(projected);charts(max);rows();$("txInv").innerHTML=inv.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}
function charts(max){let labels=[],c=[],p=[];for(let y=1;y<=max;y++){let cc=0,pp=0;inv.forEach(x=>{if(y<=+x.duration_years){cc+=+x.monthly_amount*y*12;pp+=fv(+x.monthly_amount,+x.expected_return,y)}});labels.push("Y"+y);c.push(cc);p.push(pp)}if(lc)lc.destroy();lc=new Chart($("line"),{type:"line",data:{labels,datasets:[{label:"Contribution",data:c,tension:.3,pointRadius:0},{label:"Projected",data:p,tension:.3,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#8793a7"}}},scales:{x:{ticks:{color:"#68758a"},grid:{color:"#1b2431"}},y:{ticks:{color:"#68758a",callback:v=>"৳"+(v/1e5).toFixed(0)+"L"},grid:{color:"#1b2431"}}}}});if(dc)dc.destroy();dc=new Chart($("donut"),{type:"doughnut",data:{labels:inv.map(x=>x.name),datasets:[{data:inv.map(x=>fv(+x.monthly_amount,+x.expected_return,+x.duration_years)),borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:"72%",plugins:{legend:{position:"bottom",labels:{color:"#8793a7"}}}}})}
function rows(){$("txRows").innerHTML="";$("emptyTx").style.display=tx.length?"none":"block";tx.forEach(t=>{let x=inv.find(i=>i.id===t.investment_id);$("txRows").insertAdjacentHTML("beforeend",`<tr><td>${t.transaction_date}</td><td>${esc(x?.name||"Deleted")}</td><td>${money(t.amount)}</td><td>${esc(t.note||"")}</td><td><button class="danger" onclick="delTx('${t.id}')">Delete</button></td></tr>`)})}
$("addInv").onclick=()=>{$("iid").value="";$("iname").value="";$("imonth").value="";$("irate").value="";$("iyears").value=15;$("icurrent").value=0;$("invTitle").textContent="Add investment";$("invDlg").showModal()};
window.editInv=id=>{let x=inv.find(v=>v.id===id);$("iid").value=x.id;$("iname").value=x.name;$("itype").value=x.type;$("imonth").value=x.monthly_amount;$("irate").value=x.expected_return;$("iyears").value=x.duration_years;$("icurrent").value=x.current_value;$("invTitle").textContent="Edit investment";$("invDlg").showModal()};
$("saveInv").onclick=async()=>{let id=$("iid").value,p={user_id:user.id,name:$("iname").value,type:$("itype").value,monthly_amount:+$("imonth").value,expected_return:+$("irate").value,duration_years:+$("iyears").value,current_value:+$("icurrent").value||0},q=id?sb.from("investments").update(p).eq("id",id):sb.from("investments").insert(p),{error}=await q;if(error)return toast(error.message);$("invDlg").close();load()};
window.delInv=async id=>{if(confirm("Investment delete করবেন?")){let {error}=await sb.from("investments").delete().eq("id",id);error?toast(error.message):load()}};
$("addTx").onclick=()=>{if(!inv.length)return toast("আগে investment যোগ করুন");$("txDate").value=new Date().toISOString().slice(0,10);$("txAmount").value="";$("txNote").value="";$("txDlg").showModal()};
$("saveTx").onclick=async()=>{let {error}=await sb.from("transactions").insert({user_id:user.id,investment_id:$("txInv").value,transaction_date:$("txDate").value,amount:+$("txAmount").value,note:$("txNote").value});if(error)return toast(error.message);$("txDlg").close();load()};
window.delTx=async id=>{if(confirm("Transaction delete করবেন?")){let {error}=await sb.from("transactions").delete().eq("id",id);error?toast(error.message):load()}};
state();